name: FactoryDefense
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: 18.0
    macOS: 15.0
  xcodeVersion: "26.0"
  defaultConfig: Release
packages:
  FactoryDefenseCore:
    path: .
settings:
  base:
    SWIFT_VERSION: 6.0
    DEVELOPMENT_TEAM: CQ8HGJ67R9
    CODE_SIGN_STYLE: Automatic
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    VERSIONING_SYSTEM: apple-generic
    SWIFT_EMIT_LOC_STRINGS: YES
configs:
  Debug: debug
  Release: release
targets:
  FactoryDefense_iOS:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - Apps/iOS/Sources
      - Apps/iOS/Assets.xcassets
      - path: Apps/iOS/PrivacyInfo.xcprivacy
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.factorydefense
        PRODUCT_NAME: "Factory Defense"
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: Apps/iOS/FactoryDefense.entitlements
    info:
      path: Apps/iOS/Info.plist
      properties:
        CFBundleName: "Factory Defense"
        CFBundleDisplayName: "Factory Defense"
        ITSAppUsesNonExemptEncryption: false
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
    dependencies:
      - package: FactoryDefenseCore
        product: GameSimulation
      - package: FactoryDefenseCore
        product: GameRendering
      - package: FactoryDefenseCore
        product: GameUI
      - package: FactoryDefenseCore
        product: GamePlatform
      - package: FactoryDefenseCore
        product: GameContent

  FactoryDefense_macOS:
    type: application
    platform: macOS
    deploymentTarget: "15.0"
    sources:
      - Apps/macOS/Sources
      - Apps/macOS/Assets.xcassets
      - path: Apps/macOS/PrivacyInfo.xcprivacy
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.factorydefense.macos
        PRODUCT_NAME: "Factory Defense"
        ARCHS: arm64
        ONLY_ACTIVE_ARCH: YES
        ALWAYS_SEARCH_USER_PATHS: NO
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: Apps/macOS/FactoryDefense.entitlements
    info:
      path: Apps/macOS/Info.plist
      properties:
        CFBundleName: "Factory Defense"
        CFBundleDisplayName: "Factory Defense"
        ITSAppUsesNonExemptEncryption: false
        LSMinimumSystemVersion: "15.0"
        NSPrincipalClass: NSApplication
    dependencies:
      - package: FactoryDefenseCore
        product: GameSimulation
      - package: FactoryDefenseCore
        product: GameRendering
      - package: FactoryDefenseCore
        product: GameUI
      - package: FactoryDefenseCore
        product: GamePlatform
      - package: FactoryDefenseCore
        product: GameContent

schemes:
  FactoryDefense_iOS:
    build:
      targets:
        FactoryDefense_iOS: all
    run:
      config: Debug
    test:
      config: Debug
    archive:
      config: Release

  FactoryDefense_macOS:
    build:
      targets:
        FactoryDefense_macOS: all
    run:
      config: Debug
    test:
      config: Debug
    archive:
      config: Release
